CREATE TABLE IF NOT EXISTS `agent_task_queue` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `task_id` varchar(64) NOT NULL,
  `chain_id` varchar(64) DEFAULT NULL,
  `task_type` varchar(32) NOT NULL,
  `task_status` varchar(16) NOT NULL DEFAULT 'pending',
  `priority` varchar(16) NOT NULL DEFAULT 'medium',
  `risk_level` varchar(16) NOT NULL DEFAULT 'low',
  `auto_execute` tinyint NOT NULL DEFAULT 0,
  `farm_name` varchar(125) DEFAULT NULL,
  `action_type` varchar(64) NOT NULL,
  `action_params` json DEFAULT NULL,
  `reasoning` text,
  `knowledge_refs` json DEFAULT NULL,
  `confidence_score` decimal(5,2) DEFAULT NULL,
  `approved_by` int DEFAULT NULL,
  `approved_at` datetime DEFAULT NULL,
  `executed_at` datetime DEFAULT NULL,
  `execution_result` text,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `expires_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_id` (`task_id`),
  KEY `idx_status` (`task_status`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
